ERROR    utils.MyLog:MyLog.py:42 {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '0a4e3589-f01f-4be8-ad80-790669da6257'}

Traceback (most recent call last):
  File "D:\IHRM_project\testcase\test_login.py", line 21, in test_login
    common_assert(res, expected)
  File "E:\Python\Python38\lib\site-packages\allure_commons\_allure.py", line 172, in impl
    return func(*a, **kw)
  File "D:\IHRM_project\utils\commen_assert.py", line 13, in common_assert
    assert expected.get('code') == res.json().get('code')
AssertionError