{"name": "用户名错误登陆", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <testcase.test_login.Test_login object at 0x00000160EEAECF10>\nenvironment_url = 'http://ihrm-test.itheima.net'\nask = {'mobile': '13800000003', 'password': '123456'}\nexpected = {'code': 20001, 'message': '用户名或密码错误', 'status_code': 200, 'success': False}\ntitle = '用户名错误登陆'\n\n    @allure.story('数据驱动登陆测试')\n    @allure.title('{title}')\n    @pytest.mark.parametrize('title, ask, expected', My_return_data.return_test_data('login_data.yaml'))\n    def test_login(self, environment_url, ask, expected, title):\n        try:\n            res = Login_Api().login(environment_url, ask)\n            common_assert(res, expected)\n        except Exception as e:\n            err = str(res.json()) + '\\n' + str(e)\n            MyLog.error(err)\n>           raise e\n\ntest_login.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_login.py:21: in test_login\n    common_assert(res, expected)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nres = <Response [200]>\nexpected = {'code': 20001, 'message': '用户名或密码错误', 'status_code': 200, 'success': False}\n\n    @allure.step('进行断言')\n    def common_assert(res, expected):\n        '''\n        对响应体进行断言\n        :param res: 请求响应体\n        :param expected: 字典：{success: true， code: 10000， message: '操作成功'， status_code: 200}\n        :return:assert断言\n        '''\n        assert expected.get('status_code') == res.status_code\n>       assert expected.get('code') == res.json().get('code')\nE       AssertionError\n\n..\\utils\\commen_assert.py:13: AssertionError"}, "steps": [{"name": "登陆操作", "status": "passed", "parameters": [{"name": "url", "value": "'http://ihrm-test.itheima.net'"}, {"name": "login_data", "value": "{'mobile': '13800000003', 'password': '123456'}"}], "start": 1632144080590, "stop": 1632144080665}, {"name": "进行断言", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\IHRM_project\\utils\\commen_assert.py\", line 13, in common_assert\n    assert expected.get('code') == res.json().get('code')\n"}, "parameters": [{"name": "res", "value": "<Response [200]>"}, {"name": "expected", "value": "{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'status_code': 200}"}], "start": 1632144080666, "stop": 1632144080666}], "attachments": [{"name": "log", "source": "42c8d2a9-fc8c-42b7-af1a-892090ff7ee1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "title", "value": "'用户名错误登陆'"}, {"name": "ask", "value": "{'mobile': '13800000003', 'password': '123456'}"}, {"name": "expected", "value": "{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'status_code': 200}"}], "start": 1632144080590, "stop": 1632144080667, "uuid": "f46c947e-de56-450d-a250-71af13207f66", "historyId": "14c470367e8e649d55dffdf7078fd2d1", "testCaseId": "bdb97da780450af7daf7a949f5c810d9", "fullName": "testcase.test_login.Test_login#test_login", "labels": [{"name": "epic", "value": "登陆"}, {"name": "story", "value": "数据驱动登陆测试"}, {"name": "feature", "value": "多场景登陆测试"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "LAPTOP-LM9EFOVP"}, {"name": "thread", "value": "9360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}